### ISSUE TITLE
Version Question

### ISSUE THREAD

**Issue by Amoeba00** [WireGuard/wireguard-vyatta-ubnt#18] opened 2020-05-14 05:32 UTC
Just upgraded the latest on my ER-4 and the version being reported via dpkg-query -s wireguard
is 1.0.20200506-2, not Version: 1.0.20200510.
Didn't know if that was expected or not.
Seems to work fine - no issues with in-place upgrade from 1.0.20200506-1.

**Comment by acejacek** [comment] 2020-05-14 07:32
I think it was intended; New package have only wireguard-tools updated. Module remains in version 1.0.20200506, same as in previous package. See this [commit](1.0.20200506).

**Comment by FossoresLP** [comment] 2020-05-16 15:46
Hi, sorry for the delay. Yes, this is correct and should be rather clear (in the release title, in the versions table, in the filename and in the git tag). If I've messed up somewhere please let me know. Closing for now.

**Closed by FossoresLP** 2020-05-16 15:46 UTC

**Comment by Amoeba00** [comment] 2020-05-18 02:12
No issues.  I just hadn't seen that before and wanted to make sure.  Thanks!
