### ISSUE TITLE
Upgrade to Wireguard 1.0.20201221 failed on USG3 if description field is used

### ISSUE THREAD

**Issue by yubiuser** [WireGuard/wireguard-vyatta-ubnt#63] opened 2020-12-25 13:47 UTC
I tried to upgrade from `20201112-1` to `20201221` on my USG3 via [this script](https://github.com/mafredri/vyatta-wireguard-installer).

It always failed 

```
marburger@USG:/config/scripts/post-config.d$ ./wireguard.sh upgrade    
Upgrading WireGuard...
Checking latest release for ugw3...
Downloading ugw3-v1-v1.0.20201221-v1.0.20200827.deb...
Disabling wg0...
Unloading kernel module...
Installing ugw3-v1-v1.0.20201221-v1.0.20200827.deb...
(Reading database ... 33317 files and directories currently installed.)
Preparing to replace wireguard 1.0.20201112-1 (using .../ugw3-v1-v1.0.20201221-v1.0.20200827.deb) ...
Unpacking replacement wireguard ...
Setting up wireguard (1.0.20201221-1) ...
Purging previous cache...
Caching installer to /config/user-data/wireguard/cache...
Reloading configuration...
Loading configuration from '/config/config.boot'...

Load complete.  Use 'commit' to make changes active.
[ interfaces wireguard wg0 description Remote Wireguard VPN ]
Cannot find device "wg0"

Commit failed
```

until I removed the `description field` from my `config.gateway.json`

```
				"peer": [{
						"CDXXXXXXXXXXXXXXXXXXXXYIxs=": {
							"allowed-ips": [
								"10.0.40.2/32"
							],
							"persistent-keepalive": 25,
							"description": "X230"
						}

					},
```

Immediately the update worked

```
Upgrading WireGuard...
Checking latest release for ugw3...
Downloading ugw3-v1-v1.0.20201221-v1.0.20200827.deb...
Nothing to delete (the specified node does not exist)
Unloading kernel module...
Installing ugw3-v1-v1.0.20201221-v1.0.20200827.deb...
(Reading database ... 33315 files and directories currently installed.)
Preparing to replace wireguard 1.0.20201221-1 (using .../ugw3-v1-v1.0.20201221-v1.0.20200827.deb) ...
Unpacking replacement wireguard ...
Setting up wireguard (1.0.20201221-1) ...
Purging previous cache...
Caching installer to /config/user-data/wireguard/cache...
Reloading configuration...
Loading configuration from '/config/config.boot'...
No configuration changes to commit
Upgrade complete!
``` 

Also o[thers report issues with the description field](https://community.ui.com/questions/Release-WireGuard-for-EdgeRouter/3765d2a4-1952-4629-948a-3ac9d9c22311#answer/27503fec-91b0-44b5-90d9-1896cae7eb9e).

Did anything change between those two versions regarding the `description` field?

**Comment by FossoresLP** [comment] 2020-12-25 19:52
Hi @yubiuser,
thank you for reporting this.
The issue is caused by the update script pulling a pre-release version from GitHub.
You and the other users experiencing the issue are basically unintentionally beta-testing the changes from #55.
Please report this issue to the updater script since it just checks the date of the latest commit in the release.
Also, thank you for the (unintentional) feedback regarding the changes. I will make sure they are addressed before pushing those to an actual release.

Also, whishing you a Merry Christmas in case you are celebrating.

**Comment by whiskerz007** [comment] 2020-12-26 11:07
@yubiuser You might consider using the [script](https://github.com/whiskerz007/ubnt_get_wireguard) I created. It will not install pre-released packages by default.

**Comment by yubiuser** [comment] 2020-12-26 13:11
@FossoresLP thanks for the reply.

I reported the issue to the script maintainer, which promised to fix it.

@whiskerz007 Thanks for your suggestion. However, I [saw this issue](https://github.com/whiskerz007/ubnt_get_wireguard/issues/11), which looks like the wrong release was pulled as well?

**Comment by whiskerz007** [comment] 2020-12-26 18:21
@yubiuser The op of the issue you referenced was using an older version of the script. The newest script will pull the official releases (not prerelease) according to the GitHub release page.

**Comment by FossoresLP** [comment] 2021-01-05 20:15
This is now fixed in the pre-release, too. Closing.

**Closed by FossoresLP** 2021-01-05 20:15 UTC
