### ISSUE TITLE
Wireguard / unifi not looking up new DNS entry

### ISSUE THREAD

**Issue by gareth-ellis** [WireGuard/wireguard-vyatta-ubnt#31] opened 2020-06-13 06:47 UTC
Hello,

I've recently installed wireguard on my unifi USG 3p, and have two interfaces setup. An "incoming" where the other peers connect to my USG, and an outgoing where my USG connects to wireguard running on a raspberry pi in another location. There is domain name that the raspberry pi updates when it's external IP changes

The outgoing interface is where I experienced a problem. The IP address of the raspberry pi changed and it updated the DNS record, however wireguard did not reconnect. I tried reprovisioning, but that did not do anything either. I tried taking down and bringing up the interface (/sbin/ifconfig wg1 down / /sbin/ifconfig wg1 up) I don't think this actually did anything, but it did not fix the issue either.  In the end I rebooted the USG and now all is well. 

I wasn't really expecting the other raspberry pis IP address to change very often, so I perhaps need to change it and maybe even get it to connect to my USG instead of my USG connecting to it (I have had the same IP for the past two years....even though my ISP doesn't specifically give me a static IP).

Is there any other steps I could take to force wireguard to reconnect without restarting?

Thanks

Gareth

**Comment by FossoresLP** [comment] 2020-06-13 18:25
This sounds like a duplicate of #27. Closing in favor of that issue.

**Closed by FossoresLP** 2020-06-13 18:25 UTC
